### ISSUE TITLE
Tomee + Microprofile. UnsatisfiedResolutionException.

### ISSUE THREAD

**Issue by velc0m** [rieckpil/getting-started-with-eclipse-microprofile#2]
Hi Phil!
I have the next issue with my project (tomee+Microprofile config).

**Precondition:**
Web project built on javaee(8)+tomee(8.0.0-M2-plus)+microprofile config(1.4).
In project microprifile config is used like:
```
  @Inject
  @ConfigProperty(name = "injected.value")
  private String injectedValue;
```
**Issue:**  
When I try to up tomee version to higher version (8.0.0-M3-plus, 8.0.0-plus or 8.0.1-plus) I catch exception like this:
```
org.apache.webbeans.exception.WebBeansDeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Api type [java.lang.String] is not found with the qualifiers 
Qualifiers: [@org.eclipse.microprofile.config.inject.ConfigProperty(name=injected.value, defaultValue=org.eclipse.microprofile.config.configproperty.unconfigureddvalue)]
for injection into Field Injection Point, field name :  injectedValue, Bean Owner : ...
```
For example, this my git test project: https://github.com/velc0m/mp-test.git
It's the working version. It run as "mvn clean package tomee:run".
But if you simply change in pom file version tomee from 8.0.0-M2 to 8.0.0-M3 or high then the exception occurs.

If you be so kind to look at my issue and help me,  I will be very grateful to you.
Thank you.

**Comment by rieckpil** [comment]
First hint, your MicroProfile Maven project should not contain the implementation of the MicroProfile Config API. This is shipped within the application server, so you should remove it. In addition, mark the Config API as `<provided>` :

        <dependency>
            <groupId>org.eclipse.microprofile.config</groupId>
            <artifactId>microprofile-config-api</artifactId>
            <version>1.4</version>
            <scope>provided</scope>
        </dependency>

Unfortunately, my TomEE knowledge is limited. I cloned your project and was able to run it with TomEE `8.0.1` and `<tomeeClassifier>microprofile</tomeeClassifier>`. From what I know is that TomEE+ should also be able to run MicroProfile applications, but I couldn't get it running with your application.

Please consider opening a bug/issue on the TomEE side.

These further resources might help you:

* https://www.tomitribe.com/blog/microprofile-config-on-tomee-by-david-salter/
* https://tomee.apache.org/latest/examples/
* https://www.tomitribe.com/blog/tomee-webprofile-vs-tomee-microprofile-vs-tomee-vs-tomee-plume/

**Comment by velc0m** [comment]
Philip thank you very much for your help and your time.I'll try to open issue on Tomee support. Thank you again and have a nice day. Sincerely,Vitali01.04.2020, 09:56, "Philip Riecks" <notifications@github.com>:
First hint, your MicroProfile Maven project should not contain the implementation of the MicroProfile Config API. This is shipped within the application server, so you should remove it. In addition, mark the Config API as <provided> :
    <dependency>
        <groupId>org.eclipse.microprofile.config</groupId>
        <artifactId>microprofile-config-api</artifactId>
        <version>1.4</version>
        <scope>provided</scope>
    </dependency>

Unfortunately, my TomEE knowledge is limited. I cloned your project and was able to run it with TomEE 8.0.1 and <tomeeClassifier>microprofile</tomeeClassifier>. From what I know is that TomEE+ should also be able to run MicroProfile applications, but I couldn't get it running with your application.
Please consider opening a bug/issue on the TomEE side.
These further resources might help you:

https://www.tomitribe.com/blog/microprofile-config-on-tomee-by-david-salter/
https://tomee.apache.org/latest/examples/
https://www.tomitribe.com/blog/tomee-webprofile-vs-tomee-microprofile-vs-tomee-vs-tomee-plume/


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- С уважением,Литвиненко Виталий

**Comment by rieckpil** [comment]
You are welcome @velc0m. I'll close this issue. Feel free to write me once you got an answer from the TomEE team, I'm also curious

**Comment by velc0m** [comment]
Hi Philip!I created issue on Tomee, if I get answer, I'll send you it.Thanks a lot for your help!14:20, 1 апреля 2020 г., Philip Riecks <notifications@github.com>:
You are welcome @velc0m. I'll close this issue. Feel free to write me once you got an answer from the TomEE team, I'm also curious

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты
